### ISSUE TITLE
Configuration too complex!

### ISSUE THREAD

**Issue by emilv** [Pageon/SlackWebhookMonolog#6]
Creating configuration objects seems like massive overengineering. Other Monolog handlers does not do this. Compare with the RotatingFileHandler for example:

```
new \Monolog\Handler\RotatingFileHandler($filename, 8, \Monolog\Logger::INFO, true, 0666);
```

I would expect to just provide a webhook URL, username and icon as strings.

**Comment by emilv** [comment]
https://github.com/maknz/slack is much easier to use. A thin Monolog wrapper around that should be enough, really.

**Comment by carakas** [comment]
feel free to create a PR with a factory to make it simpler to get a basic configuration.
I implemented this in a way to use all the options that are available
